# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9ca9819cdc9654db001e31263152d854dcfe4618faa2666e46959af0edd1d2f239c760cdf848f18a7cb1ddeea363c7dcdaf6cc1fcc7e6eb819d0d5c09902f2c8

test:
  secret_key_base: 7c94c6b36c381fbbdd4dd8f4a4e3280b746394d9a3a315ad433e709d994a22b8975db0044e7256246a4b27aa271ee4f14f0f29cb7e31cb934870c90d4f73925c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
